#!/bin/bash

brew install autoconf
brew install autossh 
brew install ctags
brew install gimp
brew install glide
brew install hub
brew install jq
brew install libevent
brew install openssl
brew install pkg-config
brew install rbenv
brew install rbenv-ctags
brew install rbenv-gem-rehash
brew install readline
brew install ruby-build
brew install stow
brew install tig
brew install tmux
brew install tree
brew install watch 
brew install wget
